redis:
  single:
    node: localhost:6379
    password: passwd
  cluster:
    nodes:
      - localhost:6379
      - localhost:6379
      - localhost:6379
    password: passwd

resources:
- prefix: sample
  upstream: proxy url
  expireSec: 2
  timeoutMs: 3000
  circuitBreaker:
    activeSpanSec: 3
    threshold: 5

log:
  appenders:
    stdout:
      type: stdout
    stderr:
      type: stderr
  categories:
    default:
      appenders:
      - stdout
      level: debug
    error:
      appenders:
      - stderr
      level: ERROR